### ISSUE TITLE
update to 1.20.4

### ISSUE THREAD

**Issue by lvinyl** [pdt1806/AutoDisconnect#5]
please update to 1.20.4 this is a one of kind mod that doesn't require a hack client please

**Comment by pdt1806** [comment]
@lvinyl I will try to have it updated by the end of this week. Stay tuned.

**Comment by pdt1806** [comment]
Good news! You can now download the updated mod [here](https://github.com/pdt1806/AutoDisconnect/releases/tag/v1.1.0).
